# Generated by Django 5.1.6 on 2025-07-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_category_user_customer_user_sale_user_saleitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
