# Generated by Django 5.1.6 on 2025-07-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_userprofile_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_by',
        ),
    ]
