# Generated by Django 5.1.6 on 2025-07-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_userprofile_created_by_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
