services:
  - type: web
    name: pos-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn pos_main.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: pos-db
          property: connectionString

databases:
  - name: pos-db
